import type { PersonaProfile, ProjectPersona } from "../../types/novel";
import { chatService } from "../llm/chat";

function generateId(): string {
  return `persona_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

const PERSONAS_KEY = "ai-novel-agent-personas";
const PROJECT_PERSONA_KEY = "ai-novel-agent-project-personas";

const BUILTIN_PERSONAS: Omit<PersonaProfile, "id" | "autoGenerated" | "createdAt" | "updatedAt">[] = [
  {
    name: "通用助手",
    description: "通用写作助手，适合各种类型的创作",
    genres: [],
    voiceTraits: ["自然", "流畅"],
    writingRules: [],
    styleInstruction: "请以自然流畅的风格进行写作，根据内容适配语调。",
    temperature: 0.8,
  },
  {
    name: "冷峻武侠",
    description: "擅长武侠题材，文风冷峻凌厉",
    genres: ["武侠", "仙侠"],
    voiceTraits: ["冷峻", "简洁", "画面感强"],
    writingRules: ["多用短句和动词", "每段不超过3行", "减少心理描写，以动作和对话推进情节", "环境描写服务于氛围营造"],
    styleInstruction: "你是一位冷峻的武侠小说家。使用简洁、凌厉的短句，注重动作描写和画面感。减少心理独白，通过对话和行动展现人物性格。环境描写应服务于故事氛围。",
    temperature: 0.7,
  },
  {
    name: "婉约言情",
    description: "擅长情感细腻的言情故事，文笔柔美",
    genres: ["言情", "都市", "古言"],
    voiceTraits: ["细腻", "温柔", "情感充沛"],
    writingRules: ["注重心理描写和情感流动", "多用感官细节（触、听、嗅）", "节奏舒缓，给情感留白", "对话带潜台词"],
    styleInstruction: "你是一位婉约的言情小说家。使用细腻、温柔的笔触，注重人物内心世界和情感细节。善用感官描写，让读者沉浸在情感氛围中。对话含蓄而有潜台词。",
    temperature: 0.85,
  },
  {
    name: "悬疑大师",
    description: "擅长悬疑推理，善于制造紧张感",
    genres: ["悬疑", "推理", "惊悚"],
    voiceTraits: ["紧促", "克制", "信息密度高"],
    writingRules: ["控制信息释放节奏", "每章结尾设置悬念", "细节暗示不直接点明", "用简洁冷静的语言描述紧张场景"],
    styleInstruction: "你是一位悬疑推理小说家。使用克制、精准的语言，控制信息释放的节奏。善用细节暗示和伏笔，在每章结尾制造悬念。描述紧张场景时语言要简洁冷静，让事实本身带来压迫感。",
    temperature: 0.65,
  },
  {
    name: "史诗叙事",
    description: "擅长宏大叙事的史诗奇幻，构建完整世界观",
    genres: ["奇幻", "科幻", "史诗"],
    voiceTraits: ["宏大", "庄严", "细节丰富"],
    writingRules: ["注重世界观细节", "多线叙事保持清晰", "战斗场景描写要有层次感", "人物成长弧线要明显"],
    styleInstruction: "你是一位史诗奇幻小说家。使用宏大、庄严的叙事风格，注重世界观细节和人物成长。多线叙事时保持清晰，战斗场景描写有层次感。语言华丽而不空洞，富有感染力。",
    temperature: 0.75,
  },
  {
    name: "日常治愈",
    description: "擅长日常向、生活化的治愈故事",
    genres: ["日常", "治愈", "生活"],
    voiceTraits: ["温暖", "平实", "细腻"],
    writingRules: ["描写日常细节", "注重人物互动和对话", "节奏舒缓自然", "用小事折射大情感"],
    styleInstruction: "你是一位生活化的小说家。使用温暖、平实的语言，注重日常细节和人物互动。从小事中折射情感，让读者感受到治愈和温暖。对话自然有烟火气。",
    temperature: 0.8,
  },
];

function now(): string {
  return new Date().toISOString();
}

export class PersonaService {
  private personas: PersonaProfile[] = [];
  private projectLinks: ProjectPersona[] = [];

  constructor() {
    this.load();
    if (this.personas.length === 0) {
      this.seedBuiltins();
    }
  }

  private seedBuiltins(): void {
    this.personas = BUILTIN_PERSONAS.map((p, i) => ({
      ...p,
      id: `builtin_${i}`,
      autoGenerated: false,
      createdAt: now(),
      updatedAt: now(),
    }));
    this.save();
  }

  getAll(): PersonaProfile[] {
    return [...this.personas];
  }

  getBuiltins(): PersonaProfile[] {
    return this.personas.filter((p) => p.id.startsWith("builtin_"));
  }

  getCustom(): PersonaProfile[] {
    return this.personas.filter((p) => !p.id.startsWith("builtin_"));
  }

  getById(id: string): PersonaProfile | undefined {
    return this.personas.find((p) => p.id === id);
  }

  getForProject(projectId: string): PersonaProfile | undefined {
    const link = this.projectLinks.find((l) => l.projectId === projectId);
    if (!link) return this.getBuiltins()[0];
    return this.getById(link.personaId);
  }

  setProjectPersona(projectId: string, personaId: string): void {
    const idx = this.projectLinks.findIndex((l) => l.projectId === projectId);
    if (idx >= 0) {
      this.projectLinks[idx].personaId = personaId;
    } else {
      this.projectLinks.push({ projectId, personaId });
    }
    this.save();
  }

  clearProjectPersona(projectId: string): void {
    this.projectLinks = this.projectLinks.filter((l) => l.projectId !== projectId);
    this.save();
  }

  async generatePersona(
    projectTitle: string,
    projectDescription: string,
    genre: string,
  ): Promise<PersonaProfile> {
    const prompt = [
      "请为我生成一个小说写作助手的人格配置。输出必须是严格的 JSON 格式，不要包含其他文字。",
      "",
      `小说标题：${projectTitle}`,
      `小说简介：${projectDescription}`,
      `类型/流派：${genre}`,
      "",
      "请分析以上信息，生成 JSON（只输出 JSON，不要markdown代码块）：",
      "{",
      '  "name": "人格名称（4-8个字，有特色）",',
      '  "description": "人格简介（一句话）",',
      '  "voiceTraits": ["风格特征1", "风格特征2", "风格特征3"],',
      '  "writingRules": ["具体写作规则1", "具体写作规则2", "具体写作规则3", "具体写作规则4"],',
      '  "styleInstruction": "详细的风格说明（50-100字，用"你是一位..."开头）",',
      '  "temperature": 0.6到0.9之间的数字',
      "}",
    ].join("\n");

    const raw = await chatService.sendMessage(prompt);
    const parsed = this.parsePersonaResponse(raw, projectTitle, genre);

    const profile: PersonaProfile = {
      ...parsed,
      id: generateId(),
      genres: [genre],
      autoGenerated: true,
      createdAt: now(),
      updatedAt: now(),
    };

    this.personas.push(profile);
    this.save();
    return profile;
  }

  deletePersona(id: string): boolean {
    if (id.startsWith("builtin_")) return false;
    const len = this.personas.length;
    this.personas = this.personas.filter((p) => p.id !== id);
    this.projectLinks = this.projectLinks.filter((l) => l.personaId !== id);
    if (this.personas.length !== len) {
      this.save();
      return true;
    }
    return false;
  }

  compileSystemPrompt(persona: PersonaProfile): string {
    const lines: string[] = [];
    lines.push(`## 写作人格：${persona.name}`);
    lines.push(`- ${persona.styleInstruction}`);
    if (persona.writingRules.length > 0) {
      lines.push(`- 写作规则：`);
      for (const rule of persona.writingRules) lines.push(`  - ${rule}`);
    }
    lines.push(`- 创造力温度：${persona.temperature.toFixed(1)}`);
    return lines.join("\n");
  }

  private parsePersonaResponse(
    raw: string,
    fallbackTitle: string,
    fallbackGenre: string,
  ): Omit<PersonaProfile, "id" | "genres" | "autoGenerated" | "createdAt" | "updatedAt"> {
    try {
      const cleaned = raw
        .replace(/```json\s*/g, "")
        .replace(/```\s*/g, "")
        .trim();
      const obj = JSON.parse(cleaned);
      return {
        name: obj.name || `${fallbackGenre}助手`,
        description: obj.description || `擅长${fallbackGenre}写作`,
        voiceTraits: obj.voiceTraits || [],
        writingRules: obj.writingRules || [],
        styleInstruction: obj.styleInstruction || `你是一位${fallbackGenre}小说家。请以合适的风格进行创作。`,
        temperature: typeof obj.temperature === "number" ? obj.temperature : 0.8,
      };
    } catch {
      return {
        name: `${fallbackGenre}助手`,
        description: `为「${fallbackTitle}」自动生成的写作人格`,
        voiceTraits: [],
        writingRules: [],
        styleInstruction: `你是一位擅长${fallbackGenre}题材的小说家。请根据作品内容自然地调整写作风格。`,
        temperature: 0.8,
      };
    }
  }

  private load(): void {
    try {
      const raw1 = localStorage.getItem(PERSONAS_KEY);
      if (raw1) this.personas = JSON.parse(raw1);
      const raw2 = localStorage.getItem(PROJECT_PERSONA_KEY);
      if (raw2) this.projectLinks = JSON.parse(raw2);
    } catch {
      this.personas = [];
      this.projectLinks = [];
    }
  }

  private save(): void {
    localStorage.setItem(PERSONAS_KEY, JSON.stringify(this.personas));
    localStorage.setItem(PROJECT_PERSONA_KEY, JSON.stringify(this.projectLinks));
  }
}

export const personaService = new PersonaService();
