import type { ChapterStatus } from "./chat";

export interface NovelProject {
  id: string;
  title: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export interface NovelProjectWithDetails extends NovelProject {
  chapters: Chapter[];
  characters: Character[];
  worldSettings: WorldSetting[];
}

export interface Chapter {
  id: string;
  projectId: string;
  title: string;
  content: string;
  order: number;
  summary?: string;
  wordGoal?: number;
  status?: ChapterStatus;
  notes?: string;
}

export interface Character {
  id: string;
  projectId: string;
  name: string;
  description: string;
  traits: string[];
}

export interface WorldSetting {
  id: string;
  projectId: string;
  name: string;
  description: string;
  category: string;
}

export interface PersonaProfile {
  id: string;
  name: string;
  description: string;
  genres: string[];
  voiceTraits: string[];
  writingRules: string[];
  styleInstruction: string;
  temperature: number;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectPersona {
  projectId: string;
  personaId: string;
}
